#
# Makefile - Makefile to create the doxygen documentation
#
# $Id: Makefile 3083 2008-07-02 11:04:52Z bless $
# $HeadURL: https://svn.tm.kit.edu/nsis/qspec/trunk/doc/Makefile $
#
# make		create the documentation
# make clean	delete all generated output
#
.PHONY: doxygen clean

doxygen:
	doxygen doxygen.conf

clean:
	-rm -fr html
