#! /bin/sh



# If you have the ipv4options iptables extension installed, use the uncommented rule
# default rule will pass ALL UDP data to the IP-Queue.
#
# For IPv6, there are currently no special rules known, if YOU know one filtering packets with RAO set,
# please tell us.
#
# Information on the IPv4 IP Options extension to iptables:
#
# http://www.netfilter.org/projects/patch-o-matic/pom-base.html#pom-base-ipv4options
#
# iptables -A input -m ipv4options --ra -j QUEUE
iptables -A INPUT -p udp -j QUEUE
iptables -A FORWARD -p udp -j QUEUE

# ip6tables
#ip6tables -A INPUT -p udp -m hbh --hbh-opts 5 -j QUEUE
ip6tables -A INPUT -p udp -j QUEUE
ip6tables -A FORWARD -p udp -j QUEUE
